spring.application.name=Todocalendar

spring.datasource.url=jdbc:postgresql://localhost:5432/Todocalender_db
spring.datasource.username=postgres
spring.datasource.password=melody_flag
spring.datasource.driver-class-name=org.postgresql.Driver
mybatis.mapper-locations=classpath:jp/levtech/rookie/tutorial/repository/mybatis/*.xml
mybatis.type-aliases-package=jp.levtech.rookie.tutorial.model
discord.webhook.url=https://discord.com/api/webhooks/1532668382812311625/uP8bp5Y6XrEuYcpZz7HmubCC_oklrw2h8JXZd2ufunBm1WuYdYU0HgDJ0XNnvVcv6Hty
